version: 0.2
phases:
  build:
    commands:
      - docker pull hello-world:latest
      - docker tag hello-world:latest container-release:local
      - docker save -o docker.tar container-release:local
artifacts:
  files:
    - docker.tar
